/**
 * WorkbookConfirmModal.jsx — V590
 * ══════════════════════════════════════════════════════════════════════════════
 * Confirmation modal for Full Workbook XLSX export.
 *
 * V590 changes:
 *   - Updated to reflect backend branded export (POST /v2/reports/export)
 *   - Patient Flow sheet added to sheets list (10 sheets total)
 *   - Stale "Patient Flow excluded" note removed
 *   - Audit notice updated: backend handles audit before file return
 *   - Source text updated: "verified backend export service"
 *
 * Shows:
 *   - Export type: Full Workbook XLSX
 *   - Date range
 *   - Office filter
 *   - Sheets included (10)
 *   - PHI status: aggregate-only, no patient-level PHI
 *   - Audit notice: backend logs export before returning file
 *   - Cancel / Confirm & Export buttons
 *
 * Hard rules:
 *   - No export logic here — only confirmation UI
 *   - onConfirm() triggers the export in the parent
 *   - Respects loading/disabled state during export
 */

import React from 'react';
import Icon from '../../../components/AppIcon';

const PHASE1_SHEETS = [
  'Executive Summary / Cover',
  'P&L Summary',
  'Expense Breakdown',
  'Goal Leaderboard',
  'Period Comparison',
  'Provider Production & Collections',
  'Office Comparison',
  'Treatment Plan Completion',
  'Patient Flow',
  'Source Notes / Audit Metadata',
];

const WorkbookConfirmModal = ({
  isOpen,
  onClose,
  onConfirm,
  dateStart,
  dateEnd,
  officeLabel,
  isExporting = false,
  exportProgress = null,
  exportError = null,
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50 backdrop-blur-sm"
        onClick={!isExporting ? onClose : undefined}
      />
      {/* Modal */}
      <div className="relative bg-card border border-border rounded-xl shadow-2xl w-full max-w-lg max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-border">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
              <Icon name="FileSpreadsheet" size={16} className="text-primary" />
            </div>
            <div>
              <h2 className="text-sm font-semibold text-foreground">Confirm Full Workbook Export</h2>
              <p className="text-xs text-muted-foreground">XLSX format — aggregate data only</p>
            </div>
          </div>
          {!isExporting && (
            <button
              onClick={onClose}
              className="p-1.5 rounded-md hover:bg-muted/50 text-muted-foreground hover:text-foreground transition-colors"
            >
              <Icon name="X" size={15} />
            </button>
          )}
        </div>

        {/* Body */}
        <div className="px-5 py-4 space-y-4">
          {/* Backend service notice */}
          <div className="flex items-start gap-2.5 px-3 py-2.5 bg-primary/5 border border-primary/20 rounded-lg">
            <Icon name="Server" size={14} className="text-primary flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-xs font-semibold text-foreground">Backend Export Service</p>
              <p className="text-xs text-muted-foreground mt-0.5">
                This workbook is generated by the verified backend export service. Audit logging occurs before the file is returned.
              </p>
            </div>
          </div>

          {/* Export details */}
          <div className="bg-muted/30 rounded-lg border border-border/60 p-3 space-y-2">
            <div className="flex items-center gap-2">
              <Icon name="Info" size={13} className="text-primary flex-shrink-0" />
              <p className="text-xs font-semibold text-foreground">Export Details</p>
            </div>
            <div className="grid grid-cols-2 gap-x-4 gap-y-1.5 text-xs">
              <span className="text-muted-foreground">Export Type</span>
              <span className="text-foreground font-medium">Full Workbook XLSX</span>
              <span className="text-muted-foreground">Date Range</span>
              <span className="text-foreground font-medium">{dateStart} → {dateEnd}</span>
              <span className="text-muted-foreground">Office Filter</span>
              <span className="text-foreground font-medium">{officeLabel}</span>
              <span className="text-muted-foreground">Format</span>
              <span className="text-foreground font-medium">.xlsx (Microsoft Excel)</span>
            </div>
          </div>

          {/* Sheets included */}
          <div>
            <p className="text-xs font-semibold text-foreground mb-2 flex items-center gap-1.5">
              <Icon name="Layers" size={13} className="text-muted-foreground" />
              Sheets Included ({PHASE1_SHEETS?.length})
            </p>
            <div className="space-y-1">
              {PHASE1_SHEETS?.map((sheet, i) => (
                <div key={sheet} className="flex items-center gap-2 text-xs text-foreground/80">
                  <span className="w-4 h-4 rounded-full bg-primary/10 text-primary flex items-center justify-center text-[10px] font-bold flex-shrink-0">
                    {i + 1}
                  </span>
                  {sheet}
                </div>
              ))}
            </div>
          </div>

          {/* PHI notice */}
          <div className="flex items-start gap-2.5 px-3 py-2.5 bg-emerald-50 border border-emerald-200 rounded-lg">
            <Icon name="ShieldCheck" size={14} className="text-emerald-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-xs font-semibold text-emerald-800">PHI Status: Aggregate-Only</p>
              <p className="text-xs text-emerald-700 mt-0.5">
                Aggregate-only workbook. No patient-level PHI included.
              </p>
            </div>
          </div>

          {/* Audit notice */}
          <div className="flex items-start gap-2.5 px-3 py-2.5 bg-blue-50 border border-blue-200 rounded-lg">
            <Icon name="ClipboardList" size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-xs font-semibold text-blue-800">Audit Notice</p>
              <p className="text-xs text-blue-700 mt-0.5">
                Audit logging occurs before the file is returned. The download will only proceed after the backend audit record is confirmed.
              </p>
            </div>
          </div>

          {/* Export progress */}
          {isExporting && exportProgress && (
            <div className="flex items-center gap-2.5 px-3 py-2.5 bg-primary/5 border border-primary/20 rounded-lg">
              <div className="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin flex-shrink-0" />
              <p className="text-xs text-primary font-medium">{exportProgress}</p>
            </div>
          )}

          {/* Export error */}
          {exportError && (
            <div className="flex items-start gap-2.5 px-3 py-2.5 bg-destructive/5 border border-destructive/20 rounded-lg">
              <Icon name="AlertTriangle" size={14} className="text-destructive flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-xs font-semibold text-destructive">Export Failed</p>
                <p className="text-xs text-destructive/80 mt-0.5">{exportError}</p>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-2.5 px-5 py-4 border-t border-border">
          <button
            onClick={onClose}
            disabled={isExporting}
            className="px-4 py-2 text-sm font-medium text-muted-foreground hover:text-foreground border border-border rounded-lg hover:bg-muted/50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Cancel
          </button>
          <button
            onClick={onConfirm}
            disabled={isExporting}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isExporting ? (
              <>
                <div className="w-3.5 h-3.5 border-2 border-primary-foreground border-t-transparent rounded-full animate-spin" />
                Exporting…
              </>
            ) : (
              <>
                <Icon name="Download" size={14} />
                Confirm &amp; Export
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};

export default WorkbookConfirmModal;
